// Convex Configuration
// This file configures the Convex backend

// In production, this will be auto-generated by `npx convex dev`
// The actual schema and functions are defined in convex/schema.ts and convex/functions.ts

export default {}